import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Navbar from "../../components/navbar";

// import Navbar from "@/components/navbar";

const axiforma = localFont({
  src: [
    {
      path: "./fonts/Axiforma-Thin.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-Book.woff",
      weight: "350",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-axiforma",
});

const helvetica = localFont({
  src: [
    {
      path: "./fonts/Helvetica-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Helvetica-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Axiforma-Medium.woff",
      weight: "500",
      style: "normal",
    },

    {
      path: "./fonts/Helvetica-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
        <body
          className={`${axiforma.variable} ${helvetica.variable} antialiased flex flex-col min-h-screen`}
        >
          <Navbar locale={locale} />
          <div className="flex-1">{children}</div>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
